apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: standard-test
spec:
  interval: 1m
  url: https://github.com/wsdnv/tmp-45gh84
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: standard-test
spec:
  serviceAccountName: tenant2-flux-sa
  interval: 20s
  targetNamespace: standard-test
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: "t2"
  prune: true
  timeout: 1m
